import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  gsap.registerPlugin(ScrollTrigger);

  return (
    <>
      <Head>
        <title>Maddela Sudhakar - UI/UX Designer & Graphic Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.container}>
      <h1 className={styles.maddela}>Maddela Sudhakar</h1>
      <h2>UI/UX Designer & Graphic Designer</h2>
      </div>
    </>
  )
}
